<a href="https://colab.research.google.com/github/chaitanysaraswat/Advanced-Analytics-Using-Statistics/blob/main/lecture5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/My pitch/CDAC_DataBook.xlsx',sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
a=np.random.randint(1,80,50)
df['Value']=a
df.head()

  MaterialID Location  Quantity  Value
0    TMI-43T    MWH-4        34     62
1    AXCP-78    MWH-1        67     74
2    LXCV-21    MWH-2        27     53
3    AXCP-78    MWH-5        65     21
4    AXCP-78    MWH-4        36      6

grouping will never be done on continuous or discrete data.
grouping can be done on categorical data

In [ ]:
grp1=df.groupby('MaterialID')
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [ ]:
grp1.get_group('SDRT-67')

   MaterialID Location  Quantity  Value
10    SDRT-67    MWH-1        34     29
11    SDRT-67    MWH-4        58     36
16    SDRT-67    MWH-5        12     19
17    SDRT-67    MWH-5       102     12
41    SDRT-67    MWH-1        57     12
42    SDRT-67    MWH-2        31     49

In [ ]:
grp1.Quantity.agg('mean')
grp1.Value.agg('sum')

MaterialID
AXCP-78    483
DDBN-89    308
GCVB-79    206
LXCV-21    180
SDRT-67    157
TMI-43T    562
Name: Value, dtype: int64

In [ ]:
df12=grp1.Quantity.agg(['size','mean','sum'])

In [ ]:
s1=grp1.Quantity.agg(np.size)
d1=pd.DataFrame(s1)
np.where(d1==6)
d1.loc['SDRT-67']

Quantity    6
Name: SDRT-67, dtype: int64

In [ ]:
s1=grp1.Quantity.agg(np.size)
d1=pd.DataFrame(s1)
d1.loc['SDRT-67']
np.where(d1.index=='SDRT-67')

(array([4]),)

In [ ]:
d1.iloc[np.where(d1.index=='SDRT-67')]

            Quantity
MaterialID
SDRT-67            6

In [ ]:
df12.loc['SDRT-67','sum']
df12.iloc[4,1]

np.float64(49.0)

In [ ]:
df=pd.read_excel('/content/drive/MyDrive/My pitch/CDAC_DataBook.xlsx',sheet_name='Health')
df

   Country       Disease  2019  2020  2021
0    India        Cancer    12    94    35
1       UK        Cancer    95    19    84
2       US        Cancer    98    19    53
3    Japan        Cancer    89    52    14
4    India         Covid    38    19    62
5       UK         Covid    69    73    35
6       US         Covid    87    97    35
7    Japan         Covid    14    12    90
8    India  Heart Attack    84    10    98
9       UK  Heart Attack    44    17    24
10      US  Heart Attack    34    40    54
11   Japan  Heart Attack    11    43    75

In [ ]:
df1=df.melt(id_vars=['Country','Disease'],var_name='Year',value_name='cases')#melt will increase rows id_vars will be constant var_name will create year column which will remaining column name and cases column will have every cases data
df1.head()

  Country Disease  Year  cases
0   India  Cancer  2019     12
1      UK  Cancer  2019     95
2      US  Cancer  2019     98
3   Japan  Cancer  2019     89
4   India   Covid  2019     38

In [ ]:
df.shape

(12, 5)

In [ ]:
df1.shape

(36, 4)

In [ ]:
df3=df1.pivot_table(values='cases',index=['Country','Year'],columns='Disease')#it will columns index will be consatnt and column disease will split into many columns to values of cases will have in diseases
df3

Disease       Cancer  Covid  Heart Attack
Country Year
India   2019    12.0   38.0          84.0
        2020    94.0   19.0          10.0
        2021    35.0   62.0          98.0
Japan   2019    89.0   14.0          11.0
        2020    52.0   12.0          43.0
        2021    14.0   90.0          75.0
UK      2019    95.0   69.0          44.0
        2020    19.0   73.0          17.0
        2021    84.0   35.0          24.0
US      2019    98.0   87.0          34.0
        2020    19.0   97.0          40.0
        2021    53.0   35.0          54.0

In [ ]:
df3.columns

Index(['Cancer', 'Covid', 'Heart Attack'], dtype='object', name='Disease')

In [ ]:
df3=df1.pivot_table(values='cases',index=['Country','Year'],columns='Disease').reset_index().rename_axis(columns=None)#reanme axis name above index
#it will columns index will be consatnt and column disease will split into many columns to values of cases will have in diseases
df3.head()

  Country  Year  Cancer  Covid  Heart Attack
0   India  2019    12.0   38.0          84.0
1   India  2020    94.0   19.0          10.0
2   India  2021    35.0   62.0          98.0
3   Japan  2019    89.0   14.0          11.0
4   Japan  2020    52.0   12.0          43.0

In [ ]:
df=pd.read_excel('/content/drive/MyDrive/My pitch/CDAC_DataBook.xlsx',sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
df3=df.pivot_table(values='Quantity',index=['MaterialID','Location'	],columns='Location',aggfunc='size')
df3

Location             MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID Location
AXCP-78    MWH-1       5.0    NaN    NaN    NaN    NaN
           MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-3       NaN    NaN    1.0    NaN    NaN
           MWH-4       NaN    NaN    NaN    1.0    NaN
           MWH-5       NaN    NaN    NaN    NaN    3.0
DDBN-89    MWH-1       3.0    NaN    NaN    NaN    NaN
           MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-3       NaN    NaN    1.0    NaN    NaN
           MWH-4       NaN    NaN    NaN    2.0    NaN
           MWH-5       NaN    NaN    NaN    NaN    1.0
GCVB-79    MWH-2       NaN    4.0    NaN    NaN    NaN
           MWH-5       NaN    NaN    NaN    NaN    1.0
LXCV-21    MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-3       NaN    NaN    1.0    NaN    NaN
           MWH-5       NaN    NaN    NaN    NaN    3.0
SDRT-67    MWH-1       2.0    NaN    NaN    NaN    NaN
           MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-4       NaN    NaN    NaN    1.0    NaN
           MWH-5       NaN    NaN    NaN    NaN    2.0
TMI-43T    MWH-1       1.0    NaN    NaN    NaN    NaN
           MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-3       NaN    NaN    1.0    NaN    NaN
           MWH-4       NaN    NaN    NaN   11.0    NaN
           MWH-5       NaN    NaN    NaN    NaN    1.0

In [ ]:
df3.xs('MWH-1',level=1)

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78       5.0    NaN    NaN    NaN    NaN
DDBN-89       3.0    NaN    NaN    NaN    NaN
SDRT-67       2.0    NaN    NaN    NaN    NaN
TMI-43T       1.0    NaN    NaN    NaN    NaN

In [ ]:
df3=df.pivot_table(values='Quantity',index=['MaterialID',],columns='Location',aggfunc='size')

# Statistics

# Identify types of data


*   Qualitative data(mostly in words)
*   Quantitative data(age)

- *   Discrete data(will never have decimal point it is ruled out) (will always result of counting and never will be deimal point)
- *   Continuous data(will be one where possibility of decimal point cannot be ruled out)   continuous data will alwalys result of measurement it can be measure by instrument

when n*p and n*(1-p) >10 than discrete data can be considered continuous




*   any rating or ranking is number is categorical data

Type of scale:

when the type of data is categorical it will nominal or ordinal

*   Nominal : multiple categorical data if we change it will not change result
*   Ordinal:  multiple categorical data it will have logical order if we change it will change result
*   Interval: zero  doen't absence of measurement so mathematical calculation will be operational
 doesn't mean absence of measure so mathmatical calculation/operation will be restricted ex-temperature: 0C=>0
is like  temp but zro means not like temp is not exist
cannot take Ratio
-They are comparable
- Ratio

ratio=p/qboth are continuous.
proportion=p/q both are discrete

# Descriptive stats:
- data visualization
- data summarization
# Inferential stats
- hypothesis statstics
# predictive stats
- time-series

Descriptive Stats

In [ ]:
x1=df.MaterialID
x1

0     TMI-43T
1     AXCP-78
2     LXCV-21
3     AXCP-78
4     AXCP-78
5     TMI-43T
6     TMI-43T
7     TMI-43T
8     GCVB-79
9     TMI-43T
10    SDRT-67
11    SDRT-67
12    TMI-43T
13    TMI-43T
14    TMI-43T
15    GCVB-79
16    SDRT-67
17    SDRT-67
18    TMI-43T
19    TMI-43T
20    TMI-43T
21    TMI-43T
22    DDBN-89
23    DDBN-89
24    AXCP-78
25    AXCP-78
26    DDBN-89
27    LXCV-21
28    LXCV-21
29    LXCV-21
30    DDBN-89
31    TMI-43T
32    TMI-43T
33    TMI-43T
34    GCVB-79
35    GCVB-79
36    GCVB-79
37    AXCP-78
38    AXCP-78
39    AXCP-78
40    DDBN-89
41    SDRT-67
42    SDRT-67
43    DDBN-89
44    LXCV-21
45    DDBN-89
46    AXCP-78
47    AXCP-78
48    AXCP-78
49    DDBN-89
Name: MaterialID, dtype: object

In [ ]:
len(np.unique(x1))

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [ ]:
print(x1.value_counts(),end='\n\n')
np.unique(x1,return_counts=True) # return counts will material id counts

MaterialID
TMI-43T    15
AXCP-78    11
DDBN-89     8
SDRT-67     6
GCVB-79     5
LXCV-21     5
Name: count, dtype: int64

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [ ]:
df1=x1.value_counts().reset_index()

In [ ]:
df1

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    GCVB-79      5
5    LXCV-21      5

In [ ]:
df1['Prop']=df1['count']/sum(df1['count'])
df1['pct']=df1['Prop']*100
df1

  MaterialID  count  Prop   pct
0    TMI-43T     15  0.30  30.0
1    AXCP-78     11  0.22  22.0
2    DDBN-89      8  0.16  16.0
3    SDRT-67      6  0.12  12.0
4    GCVB-79      5  0.10  10.0
5    LXCV-21      5  0.10  10.0

In [ ]:
# what pct of consignment top3 materialid contributed
x2=np.array([4,7,5,2,3,8])
np.cumsum(x2)
df1['cumsum']=np.cumsum(df1['pct'])
df1

  MaterialID  count  Prop   pct  cumsum
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    GCVB-79      5  0.10  10.0    90.0
5    LXCV-21      5  0.10  10.0   100.0

In [ ]:
df2=df1.sort_values(by='count',ascending=False)
df2

  MaterialID  count  Prop   pct  cumsum
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    GCVB-79      5  0.10  10.0    90.0
5    LXCV-21      5  0.10  10.0   100.0

In [ ]:
# centaral tendency  mean median Mode
# dispersion or variation or spread -range,inter quartile range,variance and std deviation
#shape- skewness and kurtosis

In [ ]:
# (n+1)/2

In [ ]:
x=np.array([3,4,5,6])
f=np.array([20,18,9,12])
sum((x*f)/sum(f))

np.float64(4.220338983050848)

In [ ]:
# mean should be used only when there are no extreme values in the data set
# mean should be used only when data is symetrical
# median can be used in all circumstances
#mode is only parameter which can be used for categorical data it can have more than one value