<a href="https://colab.research.google.com/github/chaitanysaraswat/Advanced-Analytics-Using-Statistics/blob/main/lecture2_numpy19_05_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a1=np.array([3,7,6,1,8,9])
a2=np.array([2,4,58,10,3,6])

in probability whenever there is and it intersection and values need to be mutiplyied.
whenever it is or it union  its values need to be added.

whenever someone ask union either in one set or in another.
whenever someone ask intersection are present in both

In [ ]:
np.intersect1d(a1,a2)

array([3, 6])

In [ ]:
np.union1d(a1,a2)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 58])

In [ ]:
# diff will give element that are present in a1 but not in a2 or we can say unique to a1 only
np.setdiff1d(a1,a2)

array([1, 7, 8, 9])

In [ ]:
# diff will give element that are presenet in a2 but not in a1 or we can say unique to a1
np.setdiff1d(a2,a1)

In [ ]:
# xorld is xor gate  which will give unique of a1 and unique of a2 ////
np.setxor1d(a1,a2)

array([ 1,  2,  4,  7,  8,  9, 10, 58])

In [ ]:
np.isin(a1,a2) # will give whether a1 value prsent a2 or not it will give true else false

array([ True, False,  True, False, False, False])

In [ ]:
np.where(np.isin(a1,a2))

(array([0, 2]),)

for matrix mutlication no of rows of a matrix is equal to no of column of b

In [ ]:
x1=np.array([2,3,-4])
x2=np.array([3,-2,1])

In [ ]:
np.dot(x1,x2) #dot product of two vectors x1 and x2

np.int64(-4)

In [ ]:
from numpy import linalg
x3=np.array([[1,2,3],[0,1,2],[1,1,0]])

In [ ]:
np.linalg.det(x3)#gives deteminant

np.float64(-1.0)

In [ ]:
np.cross(x1,x2)

array([ -5, -14, -13])

In [ ]:
np.random.rand(10) # on random 10 number in 5 ad 50

array([0.49714389, 0.63881521, 0.93165705, 0.91188045, 0.6312145 ,
       0.94618716, 0.94806885, 0.65794926, 0.14731347, 0.7485681 ])

In [ ]:
np.random.randint(10) # on random number in 5 ad 50

7

In [ ]:
np.random.randint(5,50,15) # 15 random number in 5 ad 50

array([37, 24, 23, 19, 13, 41, 45, 30,  8, 30, 18, 11, 14, 15, 33])

# PANDAS

In [ ]:
import numpy as np
import pandas as pd
from numpy import random
from numpy import linalg

In [ ]:
x1=[4,8,4,3,2]
s1=pd.Series(x1)
s1

0    4
1    8
2    4
3    3
4    2
dtype: int64

In [ ]:
s1=pd.Series(x1,index=['A','B','C','D','E']) # when we do this change labels not indices
s1

A    4
B    8
C    4
D    3
E    2
dtype: int64

In [ ]:
s1.iloc[2]# we put index/labels in integer than it will print value

np.int64(4)

In [ ]:
s1.loc['C']# we put labels in char than it will print value

np.int64(4)

In [ ]:
s1.loc[['C','A']]# we put multiple labels in char than it will print multiple value

C    4
A    4
dtype: int64

In [ ]:
s1=pd.Series(x1,index=['A','B','C','A','E']) # when we do this change labels not indices

In [ ]:
s1.loc['A']

A    4
A    3
dtype: int64

In [ ]:
s1.iloc[3]

np.int64(3)

In [ ]:
s3=pd.Series([3,9],index=['F','G'])
s3

F    3
G    9
dtype: int64

In [ ]:
s1=pd.concat([s1,s3])
s1

A    4
B    8
C    4
A    3
E    2
F    3
G    9
F    3
G    9
dtype: int64

In [ ]:
s1.iloc[4]=9
s1

A    4
B    8
C    4
A    3
E    9
F    3
G    9
F    3
G    9
dtype: int64

In [ ]:
s1.loc['E']=11
s1

A     4
B     8
C     4
A     3
E    11
F     3
G     9
F     3
G     9
dtype: int64

In [ ]:
s1.loc['F']=32
s1

A    32
B     8
C     4
A    32
E    11
F    32
G     9
F    32
G     9
dtype: int64

In [ ]:
s1.drop(['A'])

B     8
C     4
E    11
F    32
G     9
F    32
G     9
dtype: int64

In [ ]:
s1.drop(['B'])

A    32
C     4
A    32
E    11
F    32
G     9
F    32
G     9
dtype: int64

In [ ]:
s1.drop(s1.index[[2,4]])

A    32
B     8
A    32
F    32
G     9
F    32
G     9
dtype: int64

In [ ]:
s4=pd.Series([1,2,3,4,56,7,78,98,6,43,1])
s5=s4.value_counts()
print(s5,end='\n\n')
type(s5)

1     2
2     1
3     1
4     1
56    1
7     1
78    1
98    1
6     1
43    1
Name: count, dtype: int64

pandas.core.series.Series

In [ ]:
s5.iloc[1]

np.int64(1)

In [ ]:
s5.loc[1]

np.int64(2)

In [ ]:
s1

A    32
B     8
C     4
A    32
E    11
F    32
G     9
F    32
G     9
dtype: int64

In [ ]:
# how to find labels using pd.value_counts
s1.index[np.where(s1==9)[0]]

Index(['G', 'G'], dtype='object')

In [ ]:
mydata=[['A',1234,20000],['B',5678,10000],['C',1357,8000],['D',4678,30000]]

In [ ]:
len(mydata)

4

In [ ]:
len(mydata[0])

3

In [ ]:
mydf=pd.DataFrame(mydata)
mydf

   0     1      2
0  A  1234  20000
1  B  5678  10000
2  C  1357   8000
3  D  4678  30000

In [ ]:
mydf=pd.DataFrame(mydata, columns=['Name','Acco no','Balance'],index=['Sudeep','Ruchi','Arjun','Deepika'])

mydf

        Name  Acco no  Balance
Sudeep     A     1234    20000
Ruchi      B     5678    10000
Arjun      C     1357     8000
Deepika    D     4678    30000

In [ ]:
df2=mydf.iloc[1]
df2

0        B
1     5678
2    10000
Name: 1, dtype: object

In [ ]:
df2.loc[1]

np.int64(5678)

In [ ]:
df2.iloc[1]

np.int64(5678)

In [ ]:
df1=mydf.iloc[[1,2]].reset_index(drop=True)
df1.iloc[1]

0       C
1    1357
2    8000
Name: 1, dtype: object

In [ ]:
stu_info={'Name':['A','B','C','D'],'RollNo':[1,2,3,4],'Marks':[50,60,75,64]}

In [ ]:
df1=pd.DataFrame(stu_info)
df1

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64

In [ ]:
new_df=pd.DataFrame([['E',10,65],['F',7,21]],columns=df1.columns)
new_df

  Name  RollNo  Marks
0    E      10     65
1    F       7     21

In [ ]:
pd.concat([df1,new_df])

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64
0    E      10     65
1    F       7     21

In [ ]:
df2=pd.concat([df1,new_df]).reset_index(drop=True)
df2

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64
4    E      10     65
5    F       7     21

In [ ]:
x1=[67,89,75,62,59,82]
df2['marks2']=x1

In [ ]:
df2

  Name  RollNo  Marks  marks2
0    A       1     50      67
1    B       2     60      89
2    C       3     75      75
3    D       4     64      62
4    E      10     65      59
5    F       7     21      82

In [ ]:
x2=[23,34,45,54,33,21]
df2['marks3']=x2

In [ ]:
df2.shape

(6, 5)

In [ ]:
new_df3=pd.DataFrame([['G',12,34],['R',23,54]],columns=df1.columns)
new_df3
new_df3=pd.concat([df1,new_df3]).reset_index(drop=True)
new_df3

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64
4    G      12     34
5    R      23     54

In [ ]:
df2.at[3,'Marks']#we are using row label(3) and column label(marks) to extract value

np.int64(64)

In [ ]:
df2.at[3,'Marks']=79 #we are using row label(3) and column label(marks) to change value

In [ ]:
df2.iat[1,3] #we are using row index(1) and column index(3) to extract value

np.int64(89)

In [ ]:
df2.iat[1,3]=23 #we are using row index(1) and column index(3) to change value

In [ ]:
df2

  Name  RollNo  Marks  marks2  marks3
0    A       1     50      67      23
1    B       2     60      23      34
2    C       3     75      75      45
3    D       4     64      62      54
4    E      10     65      59      33
5    F       7     21      82      21

In [ ]:
df2.iloc[[0,3,5]]

  Name  RollNo  Marks  marks2  marks3
0    A       1     50      67      23
3    D       4     64      62      54
5    F       7     21      82      21

In [ ]:
df3=df2.iloc[[0,3,5]].reset_index(drop=True)# by doing this indices and row label are in sync
df3

  Name  RollNo  Marks  marks2  marks3
0    A       1     50      67      23
1    D       4     64      62      54
2    F       7     21      82      21

In [ ]:
mysub=df2[['Name','marks2']]
mysub

  Name  marks2
0    A      67
1    B      23
2    C      75
3    D      62
4    E      59
5    F      82

In [ ]:
rowextract=df2.iloc[[1,2]]
rowextract

  Name  RollNo  Marks  marks2  marks3
1    B       2     60      23      34
2    C       3     75      75      45

In [ ]:
df2.iloc[:,[1,2]]

   RollNo  Marks
0       1     50
1       2     60
2       3     75
3       4     64
4      10     65
5       7     21

In [ ]:
df2['marks2']#to help you extract column

0    67
1    23
2    75
3    62
4    59
5    82
Name: marks2, dtype: int64

In [ ]:
df2.marks2 #to help you extract single column

0    67
1    23
2    75
3    62
4    59
5    82
Name: marks2, dtype: int64

In [ ]:
df2

  Name  RollNo  Marks  marks2  marks3
0    A       1     50      67      23
1    B       2     60      23      34
2    C       3     75      75      45
3    D       4     64      62      54
4    E      10     65      59      33
5    F       7     21      82      21

In [ ]:
df2.drop([1,4],axis=0)

  Name  RollNo  Marks  marks2  marks3
0    A       1     50      67      23
2    C       3     75      75      45
3    D       4     64      62      54
5    F       7     21      82      21

In [ ]:
df2.drop(['RollNo','Marks'],axis=1)

  Name  marks2  marks3
0    A      67      23
1    B      23      34
2    C      75      45
3    D      62      54
4    E      59      33
5    F      82      21

working on excel sheet data

In [ ]:
import os

In [ ]:
os.getcwd()
os.chdir('/content/drive/MyDrive/My pitch')
os.getcwd()

'/content/drive/MyDrive/My pitch'

In [ ]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name='ERPData')
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
print(df.head(),end='\n\n')#first 5 rows
print(df.tail())# last 5 rrows

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

   MaterialID Location  Quantity
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39