<a href="https://colab.research.google.com/github/chaitanysaraswat/Advanced-Analytics-Using-Statistics/blob/main/lecture3_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
import numpy as np

In [ ]:
os.getcwd()
os.chdir('/content/drive/MyDrive/My pitch')
os.getcwd()

'/content/drive/MyDrive/My pitch'

In [ ]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name='ERPData')
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

*italicized text*

In [ ]:
df()

In [ ]:
print(df.head(),end='\n\n')
print(df.tail())

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

   MaterialID Location  Quantity
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
df.shape #result is tuple (rows,column)

(50, 3)

In [ ]:
print(np.unique(df['MaterialID']),end='\n\n')
print(np.unique(df['Location']),end='\n\n')
# print(np.unique(df['Quantity']),end='\n\n')

['AXCP-78' 'DDBN-89' 'GCVB-79' 'LXCV-21' 'SDRT-67' 'TMI-43T']

['MWH-1' 'MWH-2' 'MWH-3' 'MWH-4' 'MWH-5']

In [ ]:
print("no of unique materialid",len(np.unique(df['MaterialID'])),end='\n')
print(" no of unique location",len(np.unique(df['Location'])),end='\n\n')

no of unique materialid 6
 no of unique location 5

In [ ]:
df.columns.values# gives column name

array(['MaterialID', 'Location', 'Quantity'], dtype=object)

In [ ]:
df.columns.values[0]# will give first column

'MaterialID'

In [ ]:
df.columns.values[0]='Matid'
df.head()

     Matid Location  Quantity
0  TMI-43T    MWH-4        34
1  AXCP-78    MWH-1        67
2  LXCV-21    MWH-2        27
3  AXCP-78    MWH-5        65
4  AXCP-78    MWH-4        36

In [ ]:
df.columns.values[0]='MaterialID'
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
ind=np.where(df.Quantity>70)# will give all indices greater than 70
ind
(df.Quantity>70).sum()
len(ind[0])#length of indices greater than 70
df1=df.iloc[ind]# use iloc not loc becoz np.where output is indices (even if indices and labels are same)
df1

   MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

In [ ]:
ind=np.where((df.Quantity>70) & (df.Location=='MWH-1'))# will give all indices greater than 70 we &(Ampersand sign) operator for two conditions
df1=df.iloc[ind]
df1

   MaterialID Location  Quantity
9     TMI-43T    MWH-1       120
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
48    AXCP-78    MWH-1        75

In [ ]:
ind=np.where((df.Quantity>70))# will give all indices greater than 70 we &(Ampersand sign) operator for two conditions
df1=df.iloc[ind[0]]
df1

   MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

In [ ]:
ind=np.where((df.Quantity>70) | (df.Location=='MWH-1'))# will give all indices greater than 70 we |(pipe) operator for two conditions
df1=df.iloc[ind[0]]
df1

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
df.describe()

         Quantity
count   50.000000
mean    57.700000
std     31.887078
min     10.000000
25%     34.000000
50%     54.500000
75%     74.000000
max    152.000000

In [ ]:
df.isna().count()

MaterialID    50
Location      50
Quantity      50
dtype: int64

In [ ]:
#what will be weight of all assignments of MHW_@
temp=df.iloc[np.where(df.Location=='MWH-2')]
sum(temp.Quantity)

397

In [ ]:
# find out how many values less than 50
len(np.where(df.Quantity<50)[0])

24

In [ ]:
df1=df.drop(np.where(df.Quantity<50)[0]).reset_index(drop=True)

In [ ]:
df1.shape

(26, 3)

In [ ]:
df1.head()

  MaterialID Location  Quantity
0    AXCP-78    MWH-1        67
1    AXCP-78    MWH-5        65
2    TMI-43T    MWH-4        78
3    TMI-43T    MWH-1       120
4    SDRT-67    MWH-4        58

In [ ]:
min(df.Quantity)

10

# for: loop will be used when no of iteration are known
# while: loop will be when condition is true

In [ ]:
#adding a column by generating values based on an existing column

grade=[]
for i in df.Quantity:
    if i<=50:
        grade.append('A')
    elif i<=100:
        grade.append('B')
    else:
        grade.append('C')
df['Grade']=grade
df.head()

  MaterialID Location  Quantity Grade
0    TMI-43T    MWH-4        34     A
1    AXCP-78    MWH-1        67     B
2    LXCV-21    MWH-2        27     A
3    AXCP-78    MWH-5        65     B
4    AXCP-78    MWH-4        36     A

# .value_counts() will most used it is for frequency in descriptive analytics

In [ ]:
(df.Grade).value_counts()

Grade
A    24
B    20
C     6
Name: count, dtype: int64

In [ ]:
#lab question
# wap output warehouse highest total quantity of assignment is highest and the number is 590
# materialID and total

# *Data Cleaning*

In [ ]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='EmpInfo')
df.head()

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278

In [ ]:
ind=np.where(df.Deptt.isnull())
ind

(array([3, 5]),)

In [ ]:
ind=np.where(df.Deptt.isnull())
df1=df.iloc[ind[0]].reset_index(drop=True)
df1

     Name EmpID Deptt  Passport
0   Arjun  A342   NaN  RF453432
1  Chetan   NaN   NaN  ER534867

In [ ]:
ind=np.where(df.Deptt.isnull())
df2=df.drop(ind[0]).reset_index(drop=True)
df2

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Rishi  R475    Prodn  DF453278
4   Deepak   NaN  Quality  RF453432

Operations for data cleaning


*   remove that row  no of rows are very few
*   replace the missing value with some other value integer value(median)    string column(mode)

*   
*   List item

In [ ]:
ind=np.where(df.Deptt.isnull() & df.EmpID.isnull())
df3=df.iloc[ind[0]].reset_index(drop=True)
df3

     Name EmpID Deptt  Passport
0  Chetan   NaN   NaN  ER534867

In [ ]:
ind=np.where(df.Deptt.isnull())
print(ind[0])
df.loc[ind[0],'Deptt']='Fresher'
df.iloc[ind[0],2]='Fresher'
df

[]

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342  Fresher  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN  Fresher  ER534867
6   Deepak   NaN  Quality  RF453432

In [ ]:
df.EmpID.isnull().sum()

np.int64(2)

In [ ]:
df.EmpID.isna().sum()

np.int64(2)

In [ ]:
temp=df.dropna().reset_index(drop=True)
temp

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2    Arjun  A342  Fresher  RF453432
3    Rishi  R475    Prodn  DF453278

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   EmpID     5 non-null      object
 2   Deptt     7 non-null      object
 3   Passport  7 non-null      object
dtypes: object(4)
memory usage: 356.0+ bytes

In [ ]:
ind=np.where(df.Passport.duplicated(keep=False))[0]#keep will also help print first occurence as well other occurences of duplicates
ind
ind=np.where(df.Passport.duplicated(keep='first'))[0]#keep will also help print first occurence left as well other occurences of duplicates

ind=np.where(df.Passport.duplicated(keep='last'))[0]#keep will also help print last occurence left as well other occurences of duplicates

array([0, 2, 3, 4, 6])

In [ ]:
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
ind=np.where((df.Quantity>60) & (df.Quantity<100))
print(len(ind[0]))
df3=df.iloc[ind[0]].reset_index(drop=True)
df3

15

   MaterialID Location  Quantity
0     AXCP-78    MWH-1        67
1     AXCP-78    MWH-5        65
2     TMI-43T    MWH-4        78
3     TMI-43T    MWH-4        76
4     TMI-43T    MWH-3        65
5     GCVB-79    MWH-2        87
6     TMI-43T    MWH-4        75
7     DDBN-89    MWH-5        71
8     LXCV-21    MWH-5        83
9     TMI-43T    MWH-4        65
10    AXCP-78    MWH-5        65
11    AXCP-78    MWH-5        70
12    DDBN-89    MWH-2        69
13    AXCP-78    MWH-2        85
14    AXCP-78    MWH-1        75

In [ ]:
sum((df.Quantity>60) & (df.Quantity<100))
#GLNPS0873P

15

# Group By Command

In [169]:
grp1=df.groupby('Location')
print(grp1)
print(grp1.groups)# grouping is one on basis of location
df1=grp1.get_group('MWH-2').reset_index(drop=True)#taking out key value pair that has been created by group by on MWH-2
df2=grp1.get_group('MWH-3').reset_index(drop=True)#taking out key value pair that has been created by group by on MWH-3
df3=pd.concat([df1,df2]).reset_index(drop=True)#combining the two df using concat
df3

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7cec41962b40>
{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

   MaterialID Location  Quantity
0     LXCV-21    MWH-2        27
1     TMI-43T    MWH-2        29
2     GCVB-79    MWH-2        10
3     GCVB-79    MWH-2        87
4     GCVB-79    MWH-2        31
5     GCVB-79    MWH-2        28
6     SDRT-67    MWH-2        31
7     DDBN-89    MWH-2        69
8     AXCP-78    MWH-2        85
9     TMI-43T    MWH-3        65
10    DDBN-89    MWH-3        38
11    LXCV-21    MWH-3        42
12    AXCP-78    MWH-3        29

In [174]:
df5=grp1.Quantity.agg(np.sum).reset_index()
df5

/tmp/ipykernel_7411/61270315.py:1: FutureWarning: The provided callable <function sum at 0x7cec7d120860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df5=grp1.Quantity.agg(np.sum).reset_index()

  Location  Quantity
0    MWH-1       889
1    MWH-2       397
2    MWH-3       174
3    MWH-4       728
4    MWH-5       697

In [175]:
grp1.Quantity.agg(np.size)

Location
MWH-1    11
MWH-2     9
MWH-3     4
MWH-4    15
MWH-5    11
Name: Quantity, dtype: int64

In [177]:
df6=grp1.Quantity.agg(np.mean).reset_index()
df6

/tmp/ipykernel_7411/664160236.py:1: FutureWarning: The provided callable <function mean at 0x7cec7d121940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df6=grp1.Quantity.agg(np.mean).reset_index()

  Location   Quantity
0    MWH-1  80.818182
1    MWH-2  44.111111
2    MWH-3  43.500000
3    MWH-4  48.533333
4    MWH-5  63.363636

In [178]:
grp1.Quantity.agg(['sum','mean','size'])

          sum       mean  size
Location
MWH-1     889  80.818182    11
MWH-2     397  44.111111     9
MWH-3     174  43.500000     4
MWH-4     728  48.533333    15
MWH-5     697  63.363636    11

In [180]:
locn1=['Mumbai','Mumbai','Mumbai','Pune','Pune']
course=['AI','ML','DS','AI','DS']
marks1=[34,45,67,90,78]
marks2=[43,54,76,76,87]

In [181]:
mydf=pd.DataFrame({'Sudeep':marks1,'Ruchika':marks2},index=[locn1,course])
mydf

           Sudeep  Ruchika
Mumbai AI      34       43
       ML      45       54
       DS      67       76
Pune   AI      90       76
       DS      78       87

In [183]:
mydf.index.names=['Location','Subject']
mydf

                  Sudeep  Ruchika
Location Subject
Mumbai   AI           34       43
         ML           45       54
         DS           67       76
Pune     AI           90       76
         DS           78       87

In [184]:
mydf.loc['Mumbai','AI']
df.xs('AI',level='Subject')

Sudeep     34
Ruchika    43
Name: (Mumbai, AI), dtype: int64

In [186]:
mydf.xs('AI',level='Subject')

          Sudeep  Ruchika
Location
Mumbai        34       43
Pune          90       76